name: "Setup Environment"
description: "UDS Environment Setup"
inputs:
  gh_token:
    description: 'GITHUB_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js latest
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install UDS CLI
      shell: bash
      # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
      run: brew install defenseunicorns/tap/uds@0.8.1

    - name: Login to GHCR
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ghcr.io
        username: dummy
        password: ${{ inputs.gh_token }}
