apiVersion: v1
kind: Namespace
metadata:
  labels:
    zarf.dev/agent: ignore
  name: actions-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: actions-runner
spec:
  replicas: 4
  template:
    spec:
      repository: defenseunicorns/kibbles-AND-bits

      # https://github.com/actions/actions-runner-controller/blob/master/docs/deploying-alternative-runners.md
      image: summerwind/actions-runner-dind-rootless
      dockerdWithinRunnerContainer: true
