apiVersion: v1
kind: Namespace
metadata:
  labels:
    zarf.dev/agent: ignore
  name: actions-runner
---
# docker:dind privileged sidecar
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: default-runner-deployment
  namespace: actions-runner
spec:
  replicas: 2
  template:
    spec:
      repository: defenseunicorns/kibbles-AND-bits
      labels:
        - default
---
# no sidecar, in-container dind, privileged rootful
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dind-runner-deployment
  namespace: actions-runner
spec:
  replicas: 2
  template:
    spec:
      repository: defenseunicorns/kibbles-AND-bits
      labels:
        - dind
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
---
# no sidecar, in-container dind, privileged rootless
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dind-rootless-runner-deployment
  namespace: actions-runner
spec:
  replicas: 2
  template:
    spec:
      repository: defenseunicorns/kibbles-AND-bits
      labels:
        - dind-rootless
      image: summerwind/actions-runner-dind-rootless
      dockerdWithinRunnerContainer: true

      # Is dind without privileged possible?
      # https://github.com/actions/actions-runner-controller/blob/256e08eb4598291e94222a5a01a75e42ef8d19d2/docs/deploying-arc-runners.md?plain=1#L104-L113
---
# GitLab-style
# runner Pod creates one Pod per job in workload
# images are run via Kubernetes image: in Pods
# data is stored and transfered between Pod using a PVC
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kubernetes-runner-deployment
  namespace: actions-runner
spec:
  replicas: 2
  template:
    spec:
      repository: defenseunicorns/kibbles-AND-bits
      labels:
        - kubernetes
      containerMode: kubernetes
      serviceAccountName: runner-role
      workVolumeClaimTemplate:
        # Does not work to omit storageClassName
        # storageClassName: "my-dynamic-storage-class"
        # This results in a PVC with the following spec:
        # storageClassName: ""
        storageClassName: local-path
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      env: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: actions-runner
  name: runner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-role
  namespace: actions-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-role
  namespace: actions-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-role
subjects:
- namespace: actions-runner
  kind: ServiceAccount
  name: runner-role
