# Example UDS bundle config.  Update the values with your GitHub App values.
# This works for local development, but you will likely want to get these from GitHub Actions secrets or something like
# AWS Secrets Manager.
variables:
  actions-runner-controller:
    github_config_url: "https://github.com/my-org"
    github_app_id: "123456"
    github_app_installation_id: "12345678"
    github_runner_scaleset_name: "arc"
    github_app_private_key: my-org-runner.private-key.pem
    github_runner_storage_class: "local-path"
