name: test

on: workflow_dispatch

jobs:
  # buildah-build:
  #   strategy:
  #     matrix:
  #       label: [default, dind]
  #     fail-fast: false
  #   runs-on: [self-hosted, linux, "${{ matrix.label }}" ]
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: install buildah
  #     run: |
  #       . /etc/os-release && \
  #       sudo apt-get update && \
  #       sudo apt-get install -y ca-certificates curl gnupg2 && \
  #       echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && \
  #       curl -fsL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add - && \
  #       sudo apt-get update && \
  #       sudo apt-get install -y buildah

  #   - name: buildah build
  #     run: buildah --storage-driver=vfs bud ./server/

  # buildah-on-container-seccomp:
  #   strategy:
  #     matrix:
  #       label: [default, dind, dind-rootless, kubernetes]
  #     fail-fast: false
  #   runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

  #   container:
  #     image: ubuntu:latest
  #     options: --security-opt seccomp=unconfined
      
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: install buildah
  #     run: |
  #       apt-get update
  #       apt-get -y install buildah

  #       # fix:
  #       # error creating build container: initializing source docker://node:12: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority
  #       # update-ca-certificates

  #   - name: buidlah build
  #     run: buildah build ./server/     

  # buildah-on-container-privileged:
  #   strategy:
  #     matrix:
  #       label: [default, dind, dind-rootless, kubernetes]
  #     fail-fast: false
  #   runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

  #   container:
  #     image: ubuntu:latest
  #     options: --privileged
      
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: install buildah
  #     run: |
  #       apt-get update
  #       apt-get -y install buildah

  #       # fix:
  #       # error creating build container: initializing source docker://node:12: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority
  #       # update-ca-certificates

  #   - name: buidlah build
  #     run: buildah build ./server/


  # docker run --rm -it \
  #     -v "${PWD}:/workspace:ro" \
  #     -e BUILDAH_ISOLATION=oci \
  #     --privileged \
  #     --workdir /workspace \
  #     quay.io/buildah/stable:v1.21.0 \
  #         buildah bud -f Dockerfile
  buildah-in-rootful-privileged-container-oci-isolation:
    strategy:
      matrix:
        label: [default, dind, dind-rootless]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

    container:
      image: quay.io/buildah/stable:v1.21.0
      env:
        BUILDAH_ISOLATION: oci
      options: --privileged
      
    steps:
    - uses: actions/checkout@v3
    - name: buidlah build
      run: buildah bud ./server/

  # docker run --rm -it \
  #     -v "${PWD}:/workspace:ro" \
  #     -e BUILDAH_ISOLATION=chroot \
  #     --security-opt=seccomp=unconfined \
  #     --workdir /workspace \
  #     quay.io/buildah/stable:v1.21.0 \
  #         buildah --storage-driver=vfs bud -f Dockerfile
  buildah-in-rootful-seccomp-unconfined-container-chroot-isolation:
    strategy:
      matrix:
        label: [default, dind, dind-rootless]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

    container:
      image: quay.io/buildah/stable:v1.21.0
      env:
        BUILDAH_ISOLATION: chroot
      options: --security-opt=seccomp=unconfined
      
    steps:
    - uses: actions/checkout@v3
    - name: buidlah build
      run: buildah --storage-driver=vfs bud ./server/

  buildah-in-rootful-seccomp-unconfined-container-chroot-isolation-kubernetes:
    runs-on: [self-hosted, linux, kubernetes ]

    container:
      image: quay.io/buildah/stable:v1.21.0
      env:
        BUILDAH_ISOLATION: chroot
      # options: --security-opt=seccomp=unconfined
      
    steps:
    - uses: actions/checkout@v3
    - name: buidlah build
      run: buildah --storage-driver=vfs bud ./server/            