name: test

on: [ push,workflow_dispatch ]

jobs:
  buildah-build:
    strategy:
      matrix:
        label: [default, dind]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]
    steps:
    - uses: actions/checkout@v3

    - name: install buildah
      run: |
        sudo apt-get update
        sudo apt-get -y install buildah

    - name: buildah build
      run: buildah build ./server/

  buildah-on-container:
    strategy:
      matrix:
        label: [default, dind, dind-rootless, kubernetes]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

    container:
      image: ubuntu:latest
      options: --privileged
      
    steps:
    - uses: actions/checkout@v3

    - name: install buildah
      run: |
        apt-get update
        apt-get -y install buildah

    - name: buidlah build
      run: buildah build ./server/      