name: test

on: [ push,workflow_dispatch ]

jobs:
  buildah:
    strategy:
      matrix:
        label: [default, dind, dind-rootless]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]
    steps:
    - uses: actions/checkout@v3

    - name: install buildah
      run: |
        apt-get update
        apt-get -y install buildah

    - name: run image
      run: buildah build ./server/

  buildah2:
    strategy:
      matrix:
        label: [default, dind, dind-rootless, kubernetes]
      fail-fast: false
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]
    container:
      image: ubuntu:latest
      
    steps:
    - uses: actions/checkout@v3

    - name: install buildah
      run: |
        apt-get update
        apt-get -y install buildah

    - name: run image
      run: buildah build ./server/      