name: test

on: [ push,workflow_dispatch ]

jobs:
  buildah:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest
      
    steps:
    - uses: actions/checkout@v3
    # - name: docker build nodejs
    #   id: build-node
    #   run: |
    #     docker build ./server/ 

    - name: install buildah
      run: |
        sudo apt-get update
        sudo apt-get -y install buildah

    # - name: Buildah Action
    #   uses: redhat-actions/buildah-build@v2
    #   with:
    #     image: test-image
    #     tags: v1 ${{ github.sha }}
    #     containerfiles: |
    #       ./server/dockerfile
    - name: run image
      run: buildah build ./server/