name: image-test

on: workflow_dispatch

jobs:
  fedora:
    runs-on: ["k3d-local-runners-scaleset-001"]

    container:
      image: fedora:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release

  ubuntu:
    runs-on: ["k3d-local-runners-scaleset-001"]

    # run outside container if possible
    # container:
    #   image: ubuntu:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release
