name: image-test

on: workflow_dispatch

jobs:
  fedora:
    runs-on: ["k3d-local-runners-scaleset-001"]

    container:
      image: fedora:39
    steps:
      - name: /etc/os-release
        run: cat /etc/os-release

  ubuntu:
    runs-on: ["k3d-local-runners-scaleset-001"]

    # run outside container if possible
    container:
      image: ubuntu:22.10

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release
