name: image-test

on: workflow_dispatch

jobs:
  fedora:
    runs-on: ["runner-scale-set"]

    container:
      image: fedora:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release

  ubuntu:
    runs-on: [self-hosted, linux] # Will use an available runner at random

    container:
      image: ubuntu:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release
