name: image-test

on: workflow_dispatch

jobs:
  fedora:
    runs-on:
      group: kibbles-and-bits

    container:
      image: fedora:39
    steps:
      - name: /etc/os-release
        run: cat /etc/os-release

  ubuntu:
    runs-on:
      group: kibbles-and-bits

    # run outside container if possible
    container:
      image: ubuntu:22.10

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release
