name: image-test

on: workflow_dispatch

jobs:
  fedora:

    strategy:
      matrix:
        label: [default, dind, dind-rootless, kubernetes]
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]

    container:
      image: fedora:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release

  ubuntu:
    runs-on: [self-hosted, linux] # Will use an available runner at random

    container:
      image: ubuntu:latest

    steps:
      - name: /etc/os-release
        run: cat /etc/os-release
