name: Test ARC Bundle
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  test_bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Runner
        uses: ./.github/actions/setup-runner

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@v1.0.0
        with:
          version: v0.32.3

      - name: Create Test Bundle
        shell: bash
        run: uds run create-bundle

      # This will currently not deploy without a GitHub app setup.
      #- name: Deploy Test Bundle
      #shell: bash
      #run: uds run deploy-bundle
      #env:
      #UDS_CONFIG=./examples/uds-self-hosted-runner/uds-config.yaml

      #- name: Destroy Test Bundle
      #shell: bash
      #run: uds run destroy-bundle

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -test-bundle
