name: Test ARC Bundle
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  test_bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Runner
        uses: ./.github/actions/setup
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Test Bundle
        shell: bash
        run: uds run create-bundle --no-progress

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -test-bundle
