name: zarf-package

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  create_package:
    runs-on: ubuntu-latest

    name: ARC Zarf package
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@v1.0.0
        with:
          version: v0.27.1

      - name: Create the package
        run: zarf package create --confirm --set VERSION="${GITHUB_REF_NAME#v}"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Zarf Package
        run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/defenseunicorns/packages
        timeout-minutes: 60
