name: zarf k3d

on: workflow_dispatch

jobs:
  deploy_package:
    strategy:
      matrix:
        label: [default, dind, dind-rootless, kubernetes]
    runs-on: [self-hosted, linux, "${{ matrix.label }}" ]
    # will fail on dind-rootless: k3d doesn't work with rootless Docker
    # will fail on kubernetes: no container: specified in this workflow (and no Docker availble)

    name: Create & deploy my cool Zarf Package
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          download-init-package: true

      # - name: Create the package
      #   run: zarf package create --confirm

      - name: Create a k3d cluster
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster delete && k3d cluster create

      - name: Initialize the cluster
        run: zarf init --components=git-server --confirm

      # - name: Deploy the package
      #   run: zarf deploy --confirm

      - name: View the deployed package
        run: zarf package list